# Generated by Django 5.0.6 on 2024-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentschedule',
            name='weekday',
            field=models.CharField(default='null', editable=False, max_length=9),
        ),
    ]
