# Generated by Django 5.0.6 on 2024-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_tournamentschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
