# Generated by Django 5.0.6 on 2024-07-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
