# Generated by Django 5.0.6 on 2024-09-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_authorization_telegram_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tournamentschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.location'),
        ),
        migrations.AlterField(
            model_name='tournamentschedule',
            name='weekday',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.weekday'),
        ),
    ]
