# Generated by Django 5.0.6 on 2024-09-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_tournamentschedule_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(unique=True)),
                ('points', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
